/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ricar
 */
public class ViewCadastro extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastro
     */
    public ViewCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btCadastrar = new javax.swing.JButton();
        jtNome = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        iconin = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        FullMax = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        HideMenu = new javax.swing.JPanel();
        btHideMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Menuhide = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();

        btCadastrar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btCadastrar.setText("CADASTRAR");

        jtNome.setText("                       ");
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });

        jlNome.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jlNome.setText("NOME:");

        jtID.setText("                       ");
        jtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIDActionPerformed(evt);
            }
        });

        jlID.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jlID.setText("ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar");

        Header.setBackground(new java.awt.Color(0, 51, 51));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        iconin.setBackground(new java.awt.Color(0, 51, 51));
        iconin.setMinimumSize(new java.awt.Dimension(130, 100));
        iconin.setName(""); // NOI18N
        iconin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setBackground(new java.awt.Color(0, 51, 51));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        Close.setBackground(new java.awt.Color(0, 51, 51));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        ButtonClose.add(Close, java.awt.BorderLayout.CENTER);

        iconin.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 0, 60, 50));

        ButtonMax.setBackground(new java.awt.Color(0, 51, 51));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        FullMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FullMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        FullMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullMaxMouseExited(evt);
            }
        });
        ButtonMax.add(FullMax, java.awt.BorderLayout.CENTER);

        iconin.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, 60, 50));

        ButtonMin.setBackground(new java.awt.Color(0, 51, 51));
        ButtonMin.setLayout(new java.awt.BorderLayout());
        iconin.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 60, 50));

        Header.add(iconin, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setPreferredSize(new java.awt.Dimension(270, 254));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(0, 51, 51));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 330));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HideMenu.setBackground(new java.awt.Color(0, 51, 51));
        HideMenu.setLayout(new java.awt.BorderLayout());

        btHideMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btHideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_32px.png"))); // NOI18N
        HideMenu.add(btHideMenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(HideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, -1, -1));

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        Menuhide.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout MenuhideLayout = new javax.swing.GroupLayout(Menuhide);
        Menuhide.setLayout(MenuhideLayout);
        MenuhideLayout.setHorizontalGroup(
            MenuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        MenuhideLayout.setVerticalGroup(
            MenuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        Menu.add(Menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Dashboard.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIDActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed
    //Botão SAIR
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changeColor(ButtonClose, new Color(0,102,102));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changeColor(ButtonClose, new Color(0,51,51));
    }//GEN-LAST:event_CloseMouseExited
    //Botão Expandir
    
    
    private void FullMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseEntered
        changeColor(ButtonMax, new Color(0,102,102));
    }//GEN-LAST:event_FullMaxMouseEntered

    private void FullMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseExited
        changeColor(ButtonMax, new Color(0,51,51));
    }//GEN-LAST:event_FullMaxMouseExited

    private void FullMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FullMaxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel FullMax;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HideMenu;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Menuhide;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel btHideMenu;
    private javax.swing.JPanel iconin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
